###

In [5]:
import numpy as np,pandas as pd

In [6]:
df = pd.read_excel("DataExcel.xlsx")

In [7]:
df

,Unnamed: 0,Date,Volume,Price,MarketCap,Solution
0,0,2023-10-26 12:00:27,0.000162,0.000000,0.552864,zoc
1,1,2023-10-26 13:00:11,0.000162,0.000000,0.552259,zoc
2,2,2023-10-26 14:00:30,0.000161,0.000000,0.552044,zoc
3,3,2023-10-26 15:00:35,0.000161,0.000000,0.414440,zoc
4,4,2023-10-26 16:00:45,0.000161,0.000000,0.429934,zoc
...,...,...,...,...,...,...
731996,363,2024-01-23 00:09:10,0.000052,15159.510530,4.867986,rushai
731997,364,2024-01-23 01:08:29,0.000052,15217.928911,4.875520,rushai
731998,365,2024-01-23 02:07:41,0.000052,15286.495260,4.899674,rushai
731999,366,2024-01-23 02:29:20,0.000052,15294.655534,4.900082,rushai
732000,367,2024-01-23 03:05:30,0.000052,15294.655534,4.900082,rushai

In [8]:
df = df[["Date","Volume","Price","MarketCap","Solution"]]
df.nunique()

Date         311542
Volume       682998
Price        218330
MarketCap    538966
Solution        447
dtype: int64

In [9]:
df_lil = df.head(10000)
df_lil

                    Date    Volume         Price     MarketCap Solution
0    2023-10-26 12:00:27  0.000162  0.000000e+00  5.528645e-01      zoc
1    2023-10-26 13:00:11  0.000162  0.000000e+00  5.522594e-01      zoc
2    2023-10-26 14:00:30  0.000161  0.000000e+00  5.520441e-01      zoc
3    2023-10-26 15:00:35  0.000161  0.000000e+00  4.144396e-01      zoc
4    2023-10-26 16:00:45  0.000161  0.000000e+00  4.299342e-01      zoc
...                  ...       ...           ...           ...      ...
9995 2023-12-22 03:00:51  0.370964  3.144157e+08  1.564674e+07      zrx
9996 2023-12-22 04:00:37  0.370287  3.136456e+08  1.614479e+07      zrx
9997 2023-12-22 05:00:16  0.369679  3.130614e+08  1.657032e+07      zrx
9998 2023-12-22 06:00:04  0.373090  3.165061e+08  1.679905e+07      zrx
9999 2023-12-22 07:00:28  0.368018  3.138441e+08  1.767818e+07      zrx

[10000 rows x 5 columns]

In [55]:
dt = df
ware = []
for unique_item in dt["Solution"].unique():
    f1 = dt[dt["Solution"]==unique_item]
    f2 = list(f1.loc[:,"Price"])
    if f2[0]==0 or f2[-1]==0: continue
    f3 = [unique_item,min(f2),max(f2),f2[-1]-f2[0],(f2[-1]-f2[0])/f2[0]*100,f2[-1]]
    ware.append(f3)
ware

[['zcn',
  4286977.737503054,
  23890755.00738619,
  6873048.592850378,
  156.54789609565412,
  11263429.27778197],
 ['zrx',
  21292431.16077809,
  376690861.2073607,
  231283069.55456382,
  1056.3287994582665,
  253178058.0915777],
 ['0x0',
  78916644.39472784,
  157801631.3680137,
  -2550173.642797336,
  -2.859221490992957,
  86641015.3165339],
 ['1art',
  785397.2249009839,
  1479836.899036144,
  -405862.45155591983,
  -33.506588632841996,
  805429.0230948522],
 ['1inch',
  288610710.6464902,
  608929706.2362366,
  131635796.7206127,
  44.113083011251035,
  430041139.8407909],
 ['arms',
  21769.35817295006,
  88477.7640482636,
  17051.382595545467,
  59.35288122456868,
  45780.20290509293],
 ['42',
  1700960.2924228,
  3746547.792589641,
  -1081762.0487376037,
  -37.8890145738653,
  1773318.931604837],
 ['50c',
  15722.17375272518,
  26897.74182339958,
  3449.272910371439,
  21.78817056671271,
  19280.21612705954],
 ['mph',
  576462.9877158661,
  886134.7922465781,
  -32693.35413607466,
  -4.2716050474485705,
  732671.27515245],
 ['8pay',
  112732.21030036,
  1311595.733985229,
  456777.5304827841,
  367.58033025090396,
  581043.5732743001],
 ['aag',
  1359845.301769807,
  2140169.143735659,
  29025.417315835133,
  2.1017635411859943,
  1410028.405856426],
 ['aave',
  1129249955.412987,
  1856881554.742395,
  142955801.5772481,
  12.122485077759428,
  1322217319.824217],
 ['ghst',
  39467910.10649808,
  60867517.33637588,
  3739729.5929783806,
  8.791588120447564,
  46277318.27141612],
 ['alpha',
  0.0,
  223775431.9451979,
  78247836.33590204,
  144233.57121856487,
  78302087.11515878],
 ['fomo',
  56401.53259087109,
  100380.7139046993,
  15040.185028555934,
  25.78284148799655,
  73374.27142302117],
 ['fud',
  47895.29527556183,
  87440.12995089711,
  15269.701287155563,
  31.044452698820624,
  64456.27073740604],
 ['kek',
  79514.76247441456,
  139499.4424564644,
  24679.174620171107,
  29.29271009323279,
  108929.4011837846],
 ['aca',
  39616989.05612177,
  139954943.5550836,
  31133648.79590196,
  74.69164057290807,
  72816558.09752823],
 ['act',
  828954.7300950526,
  17804896.7695658,
  -12055215.818156833,
  -93.32740381858343,
  861907.4756515269],
 ['ac',
  141042.5034265227,
  463641.1753339975,
  25308.110921074403,
  16.02499031974452,
  183237.1356262692],
 ['acn',
  646777.6610904034,
  1517680.938603803,
  -447290.1804681771,
  -39.413011787700405,
  687589.292528004],
 ['acq',
  431465.8300433668,
  10480858.11125515,
  3025995.694682997,
  675.9140443210501,
  3473685.119116038],
 ['acx',
  15095990.08821262,
  59291512.80706254,
  29733828.948635366,
  184.8786506046218,
  45816718.37442613],
 ['acsi',
  383660.7567808955,
  545758.4672423422,
  75212.1080010634,
  19.189719196953572,
  467151.704558597],
 ['adm',
  658417.700526148,
  2685535.103602091,
  1932247.2352951635,
  288.1929994757214,
  2602717.107502432],
 ['adapad',
  3237795.006890894,
  7992996.285721574,
  1057765.6274904194,
  31.165754636480358,
  4451765.355166758],
 ['adp',
  2687182.900536169,
  6999595.200954769,
  1053585.9114718433,
  38.05758027650016,
  3821985.541236042],
 ['adax',
  174473.8130112268,
  4033118.361692754,
  -711126.9967150607,
  -77.51983230937995,
  206221.4746760648],
 ['ad',
  82918.54114599022,
  715554.9102100268,
  -583096.0022793346,
  -82.37121199927398,
  124792.091299371],
 ['ads',
  13650460.80802217,
  29977478.03114438,
  -3556907.7050548196,
  -20.574858641448014,
  13730733.32830536],
 ['agld',
  56116903.42239381,
  124125956.0319904,
  4816216.276104003,
  6.829150210019194,
  75340602.59049533],
 ['adco',
  17435816.79914792,
  26788667.56472664,
  4190136.654059019,
  23.281270403219416,
  22188023.28776949],
 ['elf',
  161919262.0869534,
  820751961.4689556,
  228087475.60933587,
  137.43875885294582,
  394043191.0952278],
 ['aera',
  142880.5327474565,
  1172125.214499439,
  465389.5040151358,
  324.83824224920056,
  608657.581318088],
 ['aergo',
  53536445.55221384,
  94785377.6830237,
  667947.2428062782,
  1.2145529645173552,
  55663263.40604253],
 ['ae',
  6502982.897614526,
  12537645.36072547,
  64191.449653284624,
  0.834631563881101,
  7755183.79060783],
 ['azr',
  198764.987266953,
  1066046.653601494,
  -273993.5922387381,
  -56.98266432267835,
  206843.1595971922],
 ['afen',
  11582.55876064009,
  249814.5623916985,
  37932.00922092626,
  298.31648762723773,
  50647.36716933584],
 ['fyn',
  3707849.254475038,
  8552167.286127767,
  185946.40096997283,
  3.0030870207416833,
  6377788.318492861],
 ['afin',
  49246.84588716602,
  175536.0175495269,
  -46204.5885097369,
  -28.258937219931816,
  117299.7504897762],
 ['afr',
  753693.9041528263,
  6562972.122134501,
  2114826.844499614,
  242.4631454543596,
  2987052.947372515],
 ['aga',
  175334.8582605899,
  263905.7870804658,
  30999.2100058308,
  17.14209886086922,
  211835.934011627],
 ['agve',
  721072.0903297263,
  1814024.987133926,
  167368.60535148496,
  20.358380374400014,
  989480.199071118],
 ['ageur',
  18351881.35766562,
  20831113.13586813,
  1144479.4525933787,
  6.23630586035435,
  19496360.810259],
 ['bld',
  56166185.90883438,
  193478191.4778924,
  48168187.62514108,
  80.3762605676887,
  108096563.5970194],
 ['dlt',
  5903.930024525667,
  71824.8789307434,
  -18722.797162096147,
  -74.54060100136158,
  6394.785619070523],
 ['aht',
  30141645.8252908,
  41355939.5363794,
  3705889.5399290733,
  12.142329954850439,
  34226304.92732924],
 ['caw',
  34233910.56435778,
  52967261.26097951,
  -5917907.346226037,
  -14.434048828569345,
  35081727.72853351],
 ['aimbot',
  5323595.076484919,
  17544605.48617723,
  -2271911.4271971527,
  -28.151590109152547,
  5798366.018546549],
 ['aimx',
  1705842.968645763,
  10723064.73519811,
  2673827.591449118,
  156.74523626121461,
  4379670.560094881],
 ['ain',
  2151676.615901082,
  3943290.49910886,
  -1147691.7410418899,
  -32.144139113558495,
  2422762.384319302],
 ['aioz',
  11771224.71219844,
  194866643.9964397,
  115905640.06853113,
  955.5200758899402,
  128035750.4652782],
 ['aipad',
  345228.8241964495,
  15621093.89951694,
  9324674.784220453,
  2099.0828744194628,
  9768900.922114097],
 ['abl',
  740910.7482254723,
  1593580.580863766,
  62768.74908624368,
  8.453992591534133,
  805243.3657437103],
 ['airi',
  0.0,
  6563995.283089225,
  2340290.375651346,
  167.684092949622,
  3735944.748397632],
 ['ator',
  44464272.46006912,
  158844864.774269,
  -43477805.16618688,
  -41.339182652571324,
  61695549.44894732],
 ['akro',
  459145.0320063064,
  870755.7846779125,
  -130147.10044298554,
  -21.37376877283082,
  478763.2972797665],
 ['adel',
  56339.10546030098,
  217614.1061814807,
  32452.98431263052,
  52.681882024230596,
  94054.77807106922],
 ['ald',
  4902813.528072527,
  23886969.30685298,
  3578009.1941194264,
  62.380501678428615,
  9313790.564657385],
 ['ala',
  473362.694044768,
  2296110.284940367,
  -147787.78989348677,
  -23.70638493666949,
  475621.4320874058],
 ['mist',
  1758182.354285469,
  2356193.914479712,
  183085.1852189789,
  10.074111190224684,
  2000468.195609353],
 ['alcx',
  25973354.34350901,
  82072512.247687,
  19463261.997880347,
  71.43223600016384,
  46710430.90609667],
 ['ach',
  75296686.33201419,
  121052122.7695584,
  -1585030.9241010845,
  -1.8683220405375973,
  83252105.80662026],
 ['rin',
  585230.1529728007,
  5465160.00561245,
  1283259.601965588,
  189.14005188358033,
  1961730.179289666],
 ['alph',
  9336434.931869926,
  171013992.586299,
  113939643.53470895,
  1209.7266575453073,
  123358270.6951542],
 ['azero',
  194048732.1274504,
  471418172.2042585,
  82550086.47550583,
  41.17360839491923,
  283042804.2468547],
 ['alex',
  30925754.81843668,
  306105673.3359182,
  138391193.88001257,
  415.8167189789857,
  171672971.0581463],
 ['sauber',
  2089881.251001171,
  7737026.992238927,
  -781736.7509051692,
  -26.478252872326998,
  2170636.106452725],
 ['algo',
  784737909.293617,
  2012149938.795937,
  495072165.1293485,
  60.92630947242574,
  1307647503.134041],
 ['alb',
  138842.2598903539,
  817850.1120495655,
  -423908.2618148017,
  -73.9022025982248,
  149698.8120087115],
 ['tlm',
  41109008.40722863,
  81864508.86764057,
  9332319.49327036,
  21.96125255940911,
  51826796.83705924],
 ['$ads',
  8997100.805004034,
  14779356.58861576,
  -551001.8488743268,
  -5.475732468560666,
  9511612.642208753],
 ['aart',
  890699.3241262322,
  4861821.689693752,
  477939.4745251527,
  49.29257321325479,
  1447536.806069278],
 ['nxra',
  47281439.61306249,
  148228580.4886236,
  41247428.60788858,
  81.35667971279143,
  91946927.10451096],
 ['allin',
  533886.7867645198,
  1376990.618121953,
  374489.2920264866,
  62.72902999751805,
  971484.4823575084],
 ['asafe',
  1521.434445762329,
  43780.45195901586,
  -1599.187925690012,
  -15.844054933968103,
  8494.111626443639],
 ['amkt',
  2991012.134979441,
  5579408.920420548,
  663460.8443825119,
  21.27654988306215,
  3781733.534404875],
 ['alpa',
  142810.9580599907,
  261081.9912424411,
  5064.484320871008,
  3.3307982955520106,
  157114.6498212612],
 ['alpaca',
  22348959.31910608,
  33021234.58558239,
  674142.2189918496,
  2.563711021254642,
  26969704.1369624],
 ['aqt',
  27884313.76559956,
  54772695.84783369,
  7621345.572958138,
  27.03558288775684,
  35811400.15620699],
 ['arbot',
  180752.7402649278,
  337191.1821593288,
  2667.432079015387,
  1.1269567120669588,
  239360.8250420008],
 ['rushai',
  12600.41448719848,
  43718.73578464054,
  -28213.888998401282,
  -64.84677734375308,
  15294.65553394968]]

In [43]:
ware

[['zcn',
  4286977.737503054,
  23890755.00738619,
  6873048.592850378,
  156.54789609565412],
 ['zrx',
  21292431.16077809,
  376690861.2073607,
  231283069.55456382,
  1056.3287994582665],
 ['0x0',
  78916644.39472784,
  157801631.3680137,
  -2550173.642797336,
  -2.859221490992957],
 ['1art',
  785397.2249009839,
  1479836.899036144,
  -405862.45155591983,
  -33.506588632841996],
 ['1inch',
  288610710.6464902,
  608929706.2362366,
  131635796.7206127,
  44.113083011251035],
 ['arms',
  21769.35817295006,
  88477.7640482636,
  17051.382595545467,
  59.35288122456868],
 ['42',
  1700960.2924228,
  3746547.792589641,
  -1081762.0487376037,
  -37.8890145738653],
 ['50c',
  15722.17375272518,
  26897.74182339958,
  3449.272910371439,
  21.78817056671271],
 ['mph',
  576462.9877158661,
  886134.7922465781,
  -32693.35413607466,
  -4.2716050474485705],
 ['8pay',
  112732.21030036,
  1311595.733985229,
  456777.5304827841,
  367.58033025090396],
 ['aag',
  1359845.301769807,
  2140169.143735659,
  29025.417315835133,
  2.1017635411859943],
 ['aave',
  1129249955.412987,
  1856881554.742395,
  142955801.5772481,
  12.122485077759428],
 ['ghst',
  39467910.10649808,
  60867517.33637588,
  3739729.5929783806,
  8.791588120447564],
 ['alpha', 0.0, 223775431.9451979, 78247836.33590204, 144233.57121856487],
 ['fomo',
  56401.53259087109,
  100380.7139046993,
  15040.185028555934,
  25.78284148799655],
 ['fud',
  47895.29527556183,
  87440.12995089711,
  15269.701287155563,
  31.044452698820624],
 ['kek',
  79514.76247441456,
  139499.4424564644,
  24679.174620171107,
  29.29271009323279],
 ['aca',
  39616989.05612177,
  139954943.5550836,
  31133648.79590196,
  74.69164057290807],
 ['acs', 0.0, 136398777.9995347, -69642723.71162899, -100.0],
 ['ace', 0.0, 5556827.452224583, -315502.5198622138, -100.0],
 ['act',
  828954.7300950526,
  17804896.7695658,
  -12055215.818156833,
  -93.32740381858343],
 ['ac',
  141042.5034265227,
  463641.1753339975,
  25308.110921074403,
  16.02499031974452],
 ['acn',
  646777.6610904034,
  1517680.938603803,
  -447290.1804681771,
  -39.413011787700405],
 ['acq',
  431465.8300433668,
  10480858.11125515,
  3025995.694682997,
  675.9140443210501],
 ['acx',
  15095990.08821262,
  59291512.80706254,
  29733828.948635366,
  184.8786506046218],
 ['acsi',
  383660.7567808955,
  545758.4672423422,
  75212.1080010634,
  19.189719196953572],
 ['adm',
  658417.700526148,
  2685535.103602091,
  1932247.2352951635,
  288.1929994757214],
 ['adapad',
  3237795.006890894,
  7992996.285721574,
  1057765.6274904194,
  31.165754636480358],
 ['adp',
  2687182.900536169,
  6999595.200954769,
  1053585.9114718433,
  38.05758027650016],
 ['adax',
  174473.8130112268,
  4033118.361692754,
  -711126.9967150607,
  -77.51983230937995],
 ['ad',
  82918.54114599022,
  715554.9102100268,
  -583096.0022793346,
  -82.37121199927398],
 ['ads',
  13650460.80802217,
  29977478.03114438,
  -3556907.7050548196,
  -20.574858641448014],
 ['agld',
  56116903.42239381,
  124125956.0319904,
  4816216.276104003,
  6.829150210019194],
 ['adco',
  17435816.79914792,
  26788667.56472664,
  4190136.654059019,
  23.281270403219416],
 ['elf',
  161919262.0869534,
  820751961.4689556,
  228087475.60933587,
  137.43875885294582],
 ['aera',
  142880.5327474565,
  1172125.214499439,
  465389.5040151358,
  324.83824224920056],
 ['aergo',
  53536445.55221384,
  94785377.6830237,
  667947.2428062782,
  1.2145529645173552],
 ['aero', 0.0, 13760073.85613293, -3387872.267270314, -100.0],
 ['ae',
  6502982.897614526,
  12537645.36072547,
  64191.449653284624,
  0.834631563881101],
 ['azr',
  198764.987266953,
  1066046.653601494,
  -273993.5922387381,
  -56.98266432267835],
 ['afen',
  11582.55876064009,
  249814.5623916985,
  37932.00922092626,
  298.31648762723773],
 ['fyn',
  3707849.254475038,
  8552167.286127767,
  185946.40096997283,
  3.0030870207416833],
 ['afin',
  49246.84588716602,
  175536.0175495269,
  -46204.5885097369,
  -28.258937219931816],
 ['afr',
  753693.9041528263,
  6562972.122134501,
  2114826.844499614,
  242.4631454543596],
 ['aga',
  175334.8582605899,
  263905.7870804658,
  30999.2100058308,
  17.14209886086922],
 ['agve',
  721072.0903297263,
  1814024.987133926,
  167368.60535148496,
  20.358380374400014],
 ['ageur',
  18351881.35766562,
  20831113.13586813,
  1144479.4525933787,
  6.23630586035435],
 ['bld',
  56166185.90883438,
  193478191.4778924,
  48168187.62514108,
  80.3762605676887],
 ['dlt',
  5903.930024525667,
  71824.8789307434,
  -18722.797162096147,
  -74.54060100136158],
 ['aht',
  30141645.8252908,
  41355939.5363794,
  3705889.5399290733,
  12.142329954850439],
 ['caw',
  34233910.56435778,
  52967261.26097951,
  -5917907.346226037,
  -14.434048828569345],
 ['ait', 0.0, 20711369.3794243, -1160984.054537134, -100.0],
 ['aimbot',
  5323595.076484919,
  17544605.48617723,
  -2271911.4271971527,
  -28.151590109152547],
 ['aimx',
  1705842.968645763,
  10723064.73519811,
  2673827.591449118,
  156.74523626121461],
 ['ain',
  2151676.615901082,
  3943290.49910886,
  -1147691.7410418899,
  -32.144139113558495],
 ['aion', 0.0, 3015502.858998618, -744418.6746401776, -100.0],
 ['aioz',
  11771224.71219844,
  194866643.9964397,
  115905640.06853113,
  955.5200758899402],
 ['aipad',
  345228.8241964495,
  15621093.89951694,
  9324674.784220453,
  2099.0828744194628],
 ['abl',
  740910.7482254723,
  1593580.580863766,
  62768.74908624368,
  8.453992591534133],
 ['airi', 0.0, 6563995.283089225, 2340290.375651346, 167.684092949622],
 ['ator',
  44464272.46006912,
  158844864.774269,
  -43477805.16618688,
  -41.339182652571324],
 ['akro',
  459145.0320063064,
  870755.7846779125,
  -130147.10044298554,
  -21.37376877283082],
 ['adel',
  56339.10546030098,
  217614.1061814807,
  32452.98431263052,
  52.681882024230596],
 ['ald',
  4902813.528072527,
  23886969.30685298,
  3578009.1941194264,
  62.380501678428615],
 ['ala',
  473362.694044768,
  2296110.284940367,
  -147787.78989348677,
  -23.70638493666949],
 ['mist',
  1758182.354285469,
  2356193.914479712,
  183085.1852189789,
  10.074111190224684],
 ['alcx',
  25973354.34350901,
  82072512.247687,
  19463261.997880347,
  71.43223600016384],
 ['ach',
  75296686.33201419,
  121052122.7695584,
  -1585030.9241010845,
  -1.8683220405375973],
 ['rin',
  585230.1529728007,
  5465160.00561245,
  1283259.601965588,
  189.14005188358033],
 ['aleph', 0.0, 42826322.5071253, -13585252.98547104, -100.0],
 ['alph',
  9336434.931869926,
  171013992.586299,
  113939643.53470895,
  1209.7266575453073],
 ['azero',
  194048732.1274504,
  471418172.2042585,
  82550086.47550583,
  41.17360839491923],
 ['ali', 0.0, 96634724.29112189, -51981991.55257473, -100.0],
 ['alex',
  30925754.81843668,
  306105673.3359182,
  138391193.88001257,
  415.8167189789857],
 ['sauber',
  2089881.251001171,
  7737026.992238927,
  -781736.7509051692,
  -26.478252872326998],
 ['algo',
  784737909.293617,
  2012149938.795937,
  495072165.1293485,
  60.92630947242574],
 ['alb',
  138842.2598903539,
  817850.1120495655,
  -423908.2618148017,
  -73.9022025982248],
 ['tlm',
  41109008.40722863,
  81864508.86764057,
  9332319.49327036,
  21.96125255940911],
 ['$ads',
  8997100.805004034,
  14779356.58861576,
  -551001.8488743268,
  -5.475732468560666],
 ['aart',
  890699.3241262322,
  4861821.689693752,
  477939.4745251527,
  49.29257321325479],
 ['nxra',
  47281439.61306249,
  148228580.4886236,
  41247428.60788858,
  81.35667971279143],
 ['allin',
  533886.7867645198,
  1376990.618121953,
  374489.2920264866,
  62.72902999751805],
 ['asafe',
  1521.434445762329,
  43780.45195901586,
  -1599.187925690012,
  -15.844054933968103],
 ['amkt',
  2991012.134979441,
  5579408.920420548,
  663460.8443825119,
  21.27654988306215],
 ['alpa',
  142810.9580599907,
  261081.9912424411,
  5064.484320871008,
  3.3307982955520106],
 ['alpaca',
  22348959.31910608,
  33021234.58558239,
  674142.2189918496,
  2.563711021254642],
 ['aqt',
  27884313.76559956,
  54772695.84783369,
  7621345.572958138,
  27.03558288775684],
 ['arbot',
  180752.7402649278,
  337191.1821593288,
  2667.432079015387,
  1.1269567120669588],
 ['rushai',
  12600.41448719848,
  43718.73578464054,
  -28213.888998401282,
  -64.84677734375308]]

In [56]:
Store = pd.DataFrame(ware,columns=["Code","Min","Max","Profit","PercentChange","Current"])
Store = Store.sort_values(by=["PercentChange"],ascending=False)
Store.to_csv("DataSorted.csv",index=False)
Store

,Code,Min,Max,Profit,PercentChange,Current
13,alpha,0.000000e+00,2.237754e+08,7.824784e+07,144233.571219,7.830209e+07
52,aipad,3.452288e+05,1.562109e+07,9.324675e+06,2099.082874,9.768901e+06
64,alph,9.336435e+06,1.710140e+08,1.139396e+08,1209.726658,1.233583e+08
1,zrx,2.129243e+07,3.766909e+08,2.312831e+08,1056.328799,2.531781e+08
51,aioz,1.177122e+07,1.948666e+08,1.159056e+08,955.520076,1.280358e+08
...,...,...,...,...,...,...
69,alb,1.388423e+05,8.178501e+05,-4.239083e+05,-73.902203,1.496988e+05
45,dlt,5.903930e+03,7.182488e+04,-1.872280e+04,-74.540601,6.394786e+03
27,adax,1.744738e+05,4.033118e+06,-7.111270e+05,-77.519832,2.062215e+05
28,ad,8.291854e+04,7.155549e+05,-5.830960e+05,-82.371212,1.247921e+05
18,act,8.289547e+05,1.780490e+07,-1.205522e+07,-93.327404,8.619075e+05

In [57]:
maxDat = Store[1:6].to_numpy().T.tolist()
minDat = Store.tail().to_numpy().T.tolist()

minDat,maxDat

([['alb', 'dlt', 'adax', 'ad', 'act'],
  [138842.2598903539,
   5903.930024525667,
   174473.8130112268,
   82918.54114599022,
   828954.7300950526],
  [817850.1120495655,
   71824.8789307434,
   4033118.361692754,
   715554.9102100268,
   17804896.7695658],
  [-423908.2618148017,
   -18722.797162096147,
   -711126.9967150607,
   -583096.0022793346,
   -12055215.818156833],
  [-73.9022025982248,
   -74.54060100136158,
   -77.51983230937995,
   -82.37121199927398,
   -93.32740381858343],
  [149698.8120087115,
   6394.785619070523,
   206221.4746760648,
   124792.091299371,
   861907.4756515269]],
 [['aipad', 'alph', 'zrx', 'aioz', 'acq'],
  [345228.8241964495,
   9336434.931869926,
   21292431.16077809,
   11771224.71219844,
   431465.8300433668],
  [15621093.89951694,
   171013992.586299,
   376690861.2073607,
   194866643.9964397,
   10480858.11125515],
  [9324674.784220453,
   113939643.53470895,
   231283069.55456382,
   115905640.06853113,
   3025995.694682997],
  [2099.0828744194628,
   1209.7266575453073,
   1056.3287994582665,
   955.5200758899402,
   675.9140443210501],
  [9768900.922114097,
   123358270.6951542,
   253178058.0915777,
   128035750.4652782,
   3473685.119116038]])

In [58]:
import json,math
def jsonify(dat):
    dic = {"Symbol":dat[0],
           "Min":dat[1],
           "Max":dat[2],
           "Profit":dat[3],
           "PercentChange":list(np.abs(dat[4]))}
    j = json.dumps(dic,indent=4)
    print(j)
    return j

minJ = jsonify(minDat)
maxJ = jsonify(maxDat)
with open("min.json","w") as f: f.write(minJ)
with open("max.json","w") as f: f.write(maxJ)

{
    "Symbol": [
        "alb",
        "dlt",
        "adax",
        "ad",
        "act"
    ],
    "Min": [
        138842.2598903539,
        5903.930024525667,
        174473.8130112268,
        82918.54114599022,
        828954.7300950526
    ],
    "Max": [
        817850.1120495655,
        71824.8789307434,
        4033118.361692754,
        715554.9102100268,
        17804896.7695658
    ],
    "Profit": [
        -423908.2618148017,
        -18722.797162096147,
        -711126.9967150607,
        -583096.0022793346,
        -12055215.818156833
    ],
    "PercentChange": [
        73.9022025982248,
        74.54060100136158,
        77.51983230937995,
        82.37121199927398,
        93.32740381858343
    ]
}
{
    "Symbol": [
        "aipad",
        "alph",
        "zrx",
        "aioz",
        "acq"
    ],
    "Min": [
        345228.8241964495,
        9336434.931869926,
        21292431.16077809,
        11771224.71219844,
        431465.8300433668
    ],
    "Max": [
        15621093.89951694,
        171013992.586299,
        376690861.2073607,
        194866643.9964397,
        10480858.11125515
    ],
    "Profit": [
        9324674.784220453,
        113939643.53470895,
        231283069.55456382,
        115905640.06853113,
        3025995.694682997
    ],
    "PercentChange": [
        2099.0828744194628,
        1209.7266575453073,
        1056.3287994582665,
        955.5200758899402,
        675.9140443210501
    ]
}

###

In [1]:
import pandas as pd,numpy as np

In [2]:
df = pd.read_csv("DataFinal_ToBeSeparated.csv")
df = df[["Symbol","Price","MarketCap","Volume"]]
df

        Symbol     Price     MarketCap    Volume
0        442.0  0.000162      0.000000  0.552864
1        442.0  0.000162      0.000000  0.552259
2        442.0  0.000161      0.000000  0.552044
3        442.0  0.000161      0.000000  0.414440
4        442.0  0.000161      0.000000  0.429934
...        ...       ...           ...       ...
731995   412.0  0.000051  15157.678622  4.856425
731996   412.0  0.000052  15159.510530  4.867986
731997   412.0  0.000052  15217.928911  4.875520
731998   412.0  0.000052  15286.495260  4.899674
731999   412.0  0.000052  15294.655534  4.900082

[732000 rows x 4 columns]

In [4]:
for unique in df["Symbol"].unique():
    d2 = df[df["Symbol"]==unique]
    d2.to_csv(f"filterseps/{unique}.csv",index=False)

###